### ISSUE TITLE
Quickly and easily provide networking of services for the developer

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2191]
***Problem***

Deploying a single micro service is straightforward with Codewind but what if I want that micro service to communicate with another micro service?  In Kubernetes, there are the service discovery options but what if I want something a lot simpler to get me up and running quickly.  We could use docker network, and label our containers but that would require the user to have knowledge of how to do that.

For example, a simple api call in my micro service would be to {url}/api/v1/blah

But, how would I know what the {url} value is?   What is the service I was connected to dropped and restarted with a different url ?

***Solution***

We could use codewind to run each of our micro services that wish to run in the same network and use codewind to provide the information on each service’s url.

For example, lets take the simple application of a front end, back end and a data base

These would be typically 3 separate micro services that would need to talk to each other.  For a novice developer, understanding how to get these all talking can be a steep learning curve but we could get codewind to do the hard work.

Let's say we get codewind to run each app and , for each app, it records the {url} of where it runs that app and associates it with an environment variable set by the user.

In the users code, they could use this env variable as part of the api call - {env variable}/api/v1/blah

Its important to note that this is in no way mean’t for production, its mean’t as an easy way for developers to quickly get up and running with a number of micro services all in communication with each other without having to worry about the network side of things.  They could then go on to use istio etc later.

As a skunkworks project, we have started on getting a PoC up and running to see if this would be viable to do

**Comment by tobespc** [comment]
# Proof of concept
## Spec
I've been working on the proof of concept for this feature, and agreed the following spec with @corbint:
* Demonstrates a local Codewind project making a HTTP request to a remote Codewind project.
* Uses `cwctl` to connect the two Codewind projects.
  * The use of `cwctl` will demonstrate how the editors will `create` and `get` networks.
* Reads an environment variable inside the local Codewind project to know the URL for the remote Codewind project.
* Both projects used are Node.js and developed through Codewind.

## Implementation
I had to make code changes to PFE and the CLI, these are tracked on branches:
* [PFE branch](https://github.com/eclipse/codewind/compare/master...james-wallis:prototype-app-communication?expand=1)
* [CLI branch](https://github.com/eclipse/codewind-installer/compare/master...james-wallis:prototype-app-communication)

The code implemented is not meant to be re-used when this feature is implemented and is purely there to demonstrate the simplicity of its design.

### Running the PoC
1. Clone both the repos / check out the branches.
2. Run Codewind and build the CLI.
3. Run Codewind with the image built on a remote Kubernetes cluster.
4. Connect to the remote Kubernetes Codewind through `cwctl connections add`.
5. Create a Node.js project both locally and on the remote Codewind.
6. Run `cwctl project network add` where `--id` is the local Codewind Node.js project ID and `--targetid` is the remote Node.js project ID.
7. Run `cwctl project network get` where `--id` is the local Codewind Node.js project ID.
8. Copy the outputted environment variable for later.
9. Make changes to the local Node.js project so that it performs a GET request to the remote Codewind project's `/health` endpoint using the environment variable copied in the previous step.
10. Run the changed code and see the connection working.

### Limitations of the PoC
This section lists the limitations of the PoC but also things we need to be careful of when implementing this functionality.

#### The PoC will not handle the changing URLs
When a project is rebuilt and relaunched (Docker container or Kubernetes Pod/Service/Ingress) the URL used to access it appears to change. I have not attempted to get around this issue for the PoC.

My gut feeling is that if this feature is implemented in the same way as the PoC and we make a simple function to reload the project if a URL changes we could end up in a loop where changing one projects URL causes another project to relaunch -> new URL -> other project restarts to get new URL -> very bad and unusable.

#### Can't communicate from remote to local
Not sure if this is possible.

#### Can't change the environment variable names 
This is something that we need in its final implementation, the ability to rename environment variables will mean that the user can use the same env names in development and production.

#### Only works for local Node.js
To get the environment variables into the Docker container I've added a simple implementation which only works for the Node.js Docker run script, this will need proper design before implementing.

**Comment by tobespc** [comment]
### Design considerations
* The default way to communicate between deployments/pods in Kube is to use a service and environment variables within the containers [see here](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#accessing-the-service).

* How to get the list of environments into the container? PoC uses a file loaded in to the Docker container using the `--env-file` option on Docker run.

* How to handle changing URLs.

* Allow the names of the generated environmnet variables to be changed so that a user can change it to the same name as their production env (if thats what they're using).

**Comment by johnmcollier** [comment]
@tobespc @james-wallis FWIW, Odo has done work in this area too, with the `odo link` command:
```
Johns-MacBook-Pro-3:~ johncollier$ odo link --help
Link component to a service or component

If the source component is not provided, the current active component is assumed.
In both use cases, link adds the appropriate secret to the environment of the source component. 
The source component can then consume the entries of the secret as environment variables.

For example:

We have created a frontend application called 'frontend' using:
odo create nodejs frontend

We've also created a backend application called 'backend' with port 8080 exposed:
odo create nodejs backend --port 8080

We can now link the two applications:
odo link backend --component frontend

Now the frontend has 2 ENV variables it can use:
COMPONENT_BACKEND_HOST=backend-app
COMPONENT_BACKEND_PORT=8080

If you wish to use a database, we can use the Service Catalog and link it to our backend:
odo service create dh-postgresql-apb --plan dev -p postgresql_user=luke -p postgresql_password=secret
odo link dh-postgresql-apb

Now backend has 2 ENV variables it can use:
DB_USER=luke
DB_PASSWORD=secret

Usage:
  odo link <service> --component [component] OR link <component> --component [component] [flags]

Examples:
  # Link the current component to the 'my-postgresql' service
  odo link my-postgresql
  
  # Link component 'nodejs' to the 'my-postgresql' service
  odo link my-postgresql --component nodejs
  
  # Link current component to the 'backend' component (backend must have a single exposed port)
  odo link backend
  
  # Link component 'nodejs' to the 'backend' component
  odo link backend --component nodejs
  
  # Link current component to port 8080 of the 'backend' component (backend must have port 8080 exposed)
  odo link backend --port 8080

Flags:
      --app string         Application, defaults to active application
      --component string   Component, defaults to active component.
      --context string     Use given context directory as a source for component settings
  -h, --help               Help for link
      --port string        Port of the backend to which to link
      --project string     Project, defaults to active project
  -w, --wait               If enabled the link will return only when the component is fully running after the link is created
      --wait-for-target    If enabled, the link command will wait for the service to be provisioned (has no effect when linking to a component)

Additional Flags:
  -v, --v Level              Log level for V logs. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging
```

Their approach was pretty simplistic IIRC, they just add env vars to the containers that contain the Kubernetes service name for the service they want to link to.

**Comment by james-wallis** [comment]
Discussed this with @tobespc yesterday and we agreed on the following process for designing and implementing this feature:
* Create document for design
    * PFE
    * cwctl
    * Implementation details / what the IDE might need to do 
* Create a list of assumptions (things that have to work, things that will need to be fixed, requirements for products such as ICPa), split the work into sections and research other technologies that can be utilised by codewind (ICPa service bindings).
* Develop PFE APIs
* Create cwctl functionality (`cwctl link` or `network` (as it was in the prototype)
    * Link two projects
    * Link multiple from files

**Comment by james-wallis** [comment]
I've PR'd a design documentation for this feature: https://github.com/codewind-resources/design-documentation/pull/17/files

My current plan (may change) is to:
* Implement local to local
* Implement remote (will be remote -> remote and local -> remote)

**Comment by james-wallis** [comment]
Development is taking place on https://github.com/eclipse/codewind/compare/master...james-wallis:project-link

I'm working by going through each project-type as some (Node.js, Spring, Liberty) have enhancements to enable them to restart quickly - bypassing a `docker build/run` on every code change. 

I'll track each project type below (Local only)
- [ ] Node.js - Network envs get added just before `nodemon` is added in the `noderun.sh` script in `src/pfe/file-watcher/scripts/nodejsScripts`.
- [ ] Spring - Same as Node.js but in `spring-start.sh` in `src/pfe/file-watcher/scripts/springScripts`.
- [ ] Swift
- [ ] Java (IDC)
- [ ] Generic Docker types (Go, Python etc)

**Comment by james-wallis** [comment]
Have appsody working with this function as the `appsodyStart()` function:
```
function appsodyStart() {

	cmd=$START_MODE

	if [ "$START_MODE" != "run" ]; then
		cmd=debug
	fi
	
	ENV_PROPERTIES_FILE=env.properties
	PROJECT_LINKS_ENV_FILE="$ROOT/.codewind-project-links.env"
	dopts=""
	if [ -f "$ENV_PROPERTIES_FILE" ] && [ -f "$PROJECT_LINKS_ENV_FILE" ]; then
		# if both files exist, merge them to resolve problem with docker-options
		TEMP_ENV_FILE="/temp_env_file.env"
		cat $ENV_PROPERTIES_FILE > $TEMP_ENV_FILE
		cat $PROJECT_LINKS_ENV_FILE >> $TEMP_ENV_FILE
		dopts=--docker-options="--env-file=$TEMP_ENV_FILE"
	elif [ -f "$ENV_PROPERTIES_FILE" ]; then
		dopts=--docker-options="--env-file=$ENV_PROPERTIES_FILE"
	elif [ -f "$PROJECT_LINKS_ENV_FILE" ]; then
		dopts=--docker-options="--env-file=$PROJECT_LINKS_ENV_FILE"
	fi

	echo "dopts= $dopts"
	
	echo "$cmd --name $CONTAINER_NAME --network codewind_network -P $dopts |& tee -a $LOG_FOLDER/appsody.log &"

	$DIR/appsody $cmd -v --name $CONTAINER_NAME --network codewind_network -P $dopts  |& tee -a $LOG_FOLDER/appsody.log &
	
	echo "APPSODY RUN DONE"
	
	$DIR/scripts/wait-for-container.sh $CONTAINER_NAME |& tee -a $LOG_FOLDER/appsody.log
}
````

I had some trouble passing in two `--env-files` through via the `--docker-options` as Appsody was appending double quotes to random places in the String. Happy to be proven wrong but at the moment the implementation above will create a temp properties file and add the contents of both the users environment variables (`env.properties`) and the networking one.

**Comment by james-wallis** [comment]
*If you're tracking this issue I've updated the design documentation to cope with applications running on the same PFE.*

Just pushed the enhancement to use the Docker network address when on the same PFE.
https://github.com/eclipse/codewind/compare/master...james-wallis:project-link#diff-06557287ee50d16fedad9d12907b150dR57

Currently the implementation is using the container IP address on the `codewind_network`. I think that the docker network IP address could change if a project is stopped and started in a different container through a code change. 
AFAIK the container names in Codewind are not likely to change or at least are far less likely to change than the Docker network address. Container names appear to be `${projectname}-${projectID}` so I'll explore this avenue but use the container ID (which is in the project.inf) to get the Container name from Docker.

**Comment by james-wallis** [comment]
The first part of this has been PR'd https://github.com/eclipse/codewind/pull/2552 which enables communication between local Docker projects.

**Comment by james-wallis** [comment]
After the code review I spoke to @markcor11 and @tobespc about sending the requests through PFE rather than straight to the application. This will mean that PFE can forward the request to the URL that it keeps up to date so we won't ever need to refresh the environment variable within a users application with a new url value.

I'm going to investigate this tomorrow based off my PR branch.
My proposed changes will be around the area of:
```
* Proj1 wants to communicate with Proj2 and both exist on the same PFE
* Proj1 has an ENV (PROJ2_ENDPOINT) which points to "codewind-pfe/api/v1/link/:idOfProj2"
* Proj1 makes a GET request to it PROJ2_ENDPOINT/api/v1/users
* PFE receives the GET request to its link endpoint, looks up the ":idOfProj2" variable that it receives from its params and forwards the request to its URL
```

**Comment by james-wallis** [comment]
Have raised a second networking PR which addresses the above. I've changed the implementation to use a proxy within PFE will receive requests from all applications with a link and forward them to the correct project. https://github.com/eclipse/codewind/pull/2571

**Comment by james-wallis** [comment]
The second PR is awaiting a review of the first but in the meantime I've created the `cwctl` commands for `cwctl project link`: https://github.com/eclipse/codewind-installer/pull/421

In addition I've started looking at the Kubernetes work:
* `Project1` communicate to PFE using its cluster IP (available as an ENV in the container)
* PFE will proxy the request to `Project2` using either it's cluster IP or `appBaseURL` which is in the project.inf file.

Currently working on adding the network envs into the project containers using a `configmap`. I'll need to:
1. load the values of an env file into the configmap
2. load all values in the configmap into the deployment/pod 

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables gives me the configmap configuration and yaml to add to the project pod to achieve both 1 and 2, I just need to see how this fits in with our current deployment system (Helm?).

**Comment by james-wallis** [comment]
While working on the Kubernetes functionality I have hit a blocker which means I cannot use the proxy. In K8s we run in HTTPS using a self signed certificate. Continuing to use the proxy would mean asking the user to make requests as `insecure` which they would need to change in production. In addition during the review for #2552 it was suggested that the proxy might add more bugs in PFE as it's another step in the process for a request to error.

I spoke to @hhellyer and @markcor11 about alternatives to the proxy and discussed using the service name (better) or cluster IP in K8s and the container name locally. Both the service names and the container names are not going to change on application restarts as they use the project name and ID.

As the container/service names are required for making requests this adds the new requirement to send back some sort of error status if the link is created before the project can launch (as the container/service name won't be available).

I'm now going to work on returning a `404` if the container/service name isn't available when a link is created and using the project container/service name as the project URL.

**Comment by james-wallis** [comment]
I've made the necessary changes to add a `configmap` into the helm chart for the default project types and to populate that `configmap` with networking data if the network env file exists.
Have verified that:
* Liberty
* Spring
* Node
* Swift
* Docker (Go, Python etc) 
all have:
* A `configmap` created for the project (have `-network` on its name so it doesn't clash with a user defined one)
* The `configmap` is populated when the project has a `.codewind-project-links.env` file
* A `envFrom` field is added with the property `configMapRef` that points to the network `configmap`.

**Comment by james-wallis** [comment]
Have now got the full flow of adding a Link, updating the configmap and restarting the project pod in K8s working. I've broken the API tests by adding in the functionality to automatically get the Docker container name locally - but I could fix this by polling the projects endpoint and waiting for the container to be running.
PR should come Tuesday or Wednesday.

**Comment by james-wallis** [comment]
Appsody PR raised: https://github.com/eclipse/codewind-appsody-extension/pull/97

**Comment by james-wallis** [comment]
PR raised to support Links in Kubernetes environments https://github.com/eclipse/codewind/pull/2667

**Comment by james-wallis** [comment]
All PR's have been delivered for this feature meaning links are supported for:
* Codewind projects (Local & K8s)
* Appsody projects (Local & K8s)

To use this feature use the `cwctl project link --help` command.

The next stage for this work is to implement project links into the IDEs.

**Comment by tobespc** [comment]
Can you record a feature in under a minute video showing this off please

**Comment by elsony** [comment]
Removing iterative dev label since this work looks like to be done within portal.

**Comment by james-wallis** [comment]
Demo project here: https://github.ibm.com/James-Wallis1/codewind-linking-demo

**Comment by james-wallis** [comment]
Support for the ODO extension:
https://github.com/eclipse/codewind/issues/3000
https://github.com/eclipse/codewind/issues/2999

**Comment by tobespc** [comment]
closing as this epic covered the initial creation of adding linking to cwctl
other issue raised for IDE
